# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='assigned_property',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_name_first',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_name_last',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_status',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='job_title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
