# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0003_auto_20160105_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittal_year', models.IntegerField(default=0)),
                ('submittal_month', models.IntegerField(default=0)),
                ('pm_submitted', models.IntegerField(default=0)),
                ('rm_approved', models.IntegerField(default=0)),
                ('payroll_submitted', models.IntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('op_rev_month_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('op_rev_month_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('noi_semi_ann_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('noi_semi_ann_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('op_rev_qtr_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('op_rev_qtr_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lease_up_override', models.IntegerField(default=0)),
                ('delinquency_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bad_debt_writeoffs', models.IntegerField(default=0)),
                ('data_complete', models.IntegerField(default=0)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
