# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='leasing_status',
            field=models.CharField(default='stabilized', max_length=20),
        ),
    ]
