# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0002_submittal_leasing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='delinquency_rate',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='leasing_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='noi_semi_ann_actual',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='noi_semi_ann_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='occupancy_rate',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='op_rev_month_actual',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='op_rev_month_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='op_rev_qtr_actual',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='op_rev_qtr_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
