# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_auto_20160105_1547'),
        ('submittal', '0002_submittal_leasing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submittal_Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_sharing_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('failed_shops', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employees')),
                ('submittal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submittal.Submittal')),
            ],
        ),
    ]
