# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20151223_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_opening',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='date_stabilization',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fiscal_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_number_jde',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_number_yardi',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
